### ISSUE TITLE
Unable to uninstall bootstrap3-plus

### ISSUE THREAD

**Issue by taziobaker** [jonayad/bootstrap3-plus#1]
Trying to uninstall Bootstrap3-plus, but I keep getting message:
Failed to delete bootstrap3-plus: Does not exist
Please help.
Image attached for clarification
![bootstarp3-plus](https://cloud.githubusercontent.com/assets/4944001/15199296/03cbccaa-17ab-11e6-973f-e503c469c2c1.png)

**Comment by taziobaker** [comment]
Attempted multiple times.
Rebooted Atom and it disappeared.

**Comment by jonayad** [comment]
Thanks for opening and closing the issue ! 
I think the installation process somehow interrupted.
I will mark it as a bug if it affected multiple user.

**Comment by jonayad** [comment]
Thanks for opening and closing the issue !
I think the installation process somehow interrupted.
I will mark it as a bug if it affected multiple user.
